---
- name: Configuraci칩n general de los servidores
  hosts: all
  become: true
  tasks:
    - name: Actualizar APT
      apt: update_cache=yes      

- name: Configuraci칩n de la base de datos
  hosts: database
  become: true
  tasks:
    - name: Instalar MySQL
      apt:
        name:
          - mariadb-server-10.3
          - python3-mysqldb
        state: latest 

    - name: Cambiar la contrase침a de root
      mysql_user:
        name: root
        password: pass
        login_password: ''
        login_unix_socket: /var/run/mysqld/mysqld.sock
      tags: [ mysql, mysql-root ]

    - name: Crear un usuario
      mysql_db:
        name: wordpress
        state: present
        login_user: root
        login_password: pass
      tags: [ mysql ]

    - name: Crear una base de datos
      mysql_user:
        name: wordpress
        password: wordpress
        priv: "wordpress.*:ALL"
        state: present
        login_user: root
        login_password: pass
      tags: [ mysql ]

- name: Configuraci칩n del web server
  hosts: webserver
  become: true
  tasks:
    - name: Instalar nginx
      apt: name=nginx state=latest
      become: yes      

    - name: Instalar PHP y sus extensiones para Wordpress
      apt:
        name:
          - php-fpm
          - php-mysql
          - php-curl
          - php-gd
          - php-intl
          - php-mbstring
          - php-soap
          - php-xml
          - php-xmlrpc
          - php-zip          
        state: latest 
      become: yes

    - name: Copiar archivo de configuracion de Nginx
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/wordpress
      become: yes

    - name: Configurar Wordpress en Nginx
      shell: |        
        cd /var/www/
        wget https://www.wordpress.org/latest.tar.gz
        tar xf latest.tar.gz
        chown -R www-data: /var/www/wordpress
        rm -r latest.tar.gz
        rm /etc/nginx/sites-enabled/default
        ln -s /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/wordpress
      become: yes

    - name: Arrancar PHP
      service:
        name: php7.4-fpm
        state: started
      become: yes

    - name: Arrancar nginx
      service:
        name: nginx
        state: started      
      become: yes
